# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zoo-fleet
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: zoo-fleet-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: |-
          postgresql://{{ .ZOO_FLEET_POSTGRES_USER | urlquery | replace "+" "%20" }}:{{ .ZOO_FLEET_POSTGRES_PASS | urlquery | replace "+" "%20" }}@postgres17-pooler.database.svc.cluster.local:5432/zoo_fleet?sslmode=disable
        FLEET_MQTT_PASSWORD: "{{ .MOSQUITTO_ADMIN_PASSWORD }}"
        FLEET_MQTT_USERNAME: "{{ .MOSQUITTO_ADMIN_USERNAME }}"
        FLEET_OPERATOR_TOKEN_SHA256: "{{ .OPERATOR_TOKEN_SHA256 }}"
        FLEET_PUBLISH_TOKEN_SHA256: "{{ .PUBLISH_TOKEN_SHA256 }}"
        FLEET_SIGNING_KEY_ID: "{{ .SIGNING_KEY_ID }}"
        FLEET_SIGNING_PRIVATE_KEY_REF: "{{ .SIGNING_PRIVATE_KEY_REF }}"
        FLEET_SIGNING_PUBLIC_KEY_BASE64: "{{ .SIGNING_PUBLIC_KEY_BASE64 }}"
        INIT_POSTGRES_DBNAME: zoo_fleet
        INIT_POSTGRES_HOST: postgres17-pooler.database.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .ZOO_FLEET_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: "{{ .ZOO_FLEET_POSTGRES_USER }}"
  data:
  - secretKey: MOSQUITTO_ADMIN_PASSWORD
    remoteRef:
      key: mosquitto
      property: ADMIN_PASSWORD
  - secretKey: MOSQUITTO_ADMIN_USERNAME
    remoteRef:
      key: mosquitto
      property: ADMIN_USERNAME
  dataFrom:
  - extract:
      key: zoo-fleet
  - extract:
      key: cloudnative-pg
