# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: zoo-fleet
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:b2700547a3470e16eec17c8568262c6f40c26bac3c22aa9a5a79cd77d466fcc6
  secretRef:
    name: ghcr-pull-secret
  url: oci://ghcr.io/thezoo-house/charts/zoo-fleet
