# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: zoo-fleet
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:d75f04ebfbbaf5741be1d1487d00a2edf16eaf3b065c72d44be196bf23d67f85
  secretRef:
    name: ghcr-pull-secret
  url: oci://ghcr.io/thezoo-house/charts/zoo-fleet
