apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: profilarr-hermes-machine
  namespace: arrs
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: profilarr-envoy-api-hermes
  authorization:
    defaultAction: Deny
    rules:
    - name: allow-hermes-mac
      action: Allow
      principal:
        clientCIDRs:
        - 10.0.10.95/32
