# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: node-feature-discovery
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  postRenderers:
  - kustomize:
      images:
      - name: registry.k8s.io/nfd/node-feature-discovery
        newName: registry.k8s.io/nfd/node-feature-discovery
        # renovate: datasource=docker depName=registry.k8s.io/nfd/node-feature-discovery
        newTag: v0.19.0@sha256:2fa1c99ad09bdf2c8ad97706a4ad2fd548c84d5ecd70ba32a6152c667b96c4d2
  values:
    worker:
      config:
        core:
          sources: ["pci", "system", "usb"]
    prometheus:
      enable: true
