# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
spec:
  interval: 10m
  values:
    controllers:
      radarr:
        containers:
          kopiur-postgres:
            image:
              repository: docker.io/library/postgres
              tag: 17@sha256:2d2b8998d31037bf721cfdf764d76ba74171b4fab3431b7f72c27c56ddbdf9e3
            command: [sleep, infinity]
            env:
              PGHOST: postgres17-rw.database.svc.cluster.local
              PGPORT: "5432"
              PGDATABASES: radarr_main
              CAPTURE_MODE: single-db-stable-filetree
              PGSSLMODE: require
              CONFIG_FILE: /config/config.xml
            envFrom:
            - secretRef:
                name: radarr-kopiur-postgres
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: {drop: [ALL]}
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                memory: 512Mi
    persistence:
      kopiur-postgres-script:
        type: configMap
        name: radarr-kopiur-postgres
        advancedMounts:
          radarr:
            kopiur-postgres:
            - path: /kopiur
              readOnly: true
      media:
        globalMounts: null
        advancedMounts:
          radarr:
            app:
            - path: /media
