# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bazarr-kopiur-grant-identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: bazarr-kopiur-grant-identity
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PGUSER: '{{ .PG_BACKUP_USER }}'
        PGPASSWORD: '{{ .PG_BACKUP_PASSWORD }}'
  dataFrom:
  - extract:
      key: kopiur-bazarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-kopiur-grant-identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: radarr-kopiur-grant-identity
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PGUSER: '{{ .PG_BACKUP_USER }}'
        PGPASSWORD: '{{ .PG_BACKUP_PASSWORD }}'
  dataFrom:
  - extract:
      key: kopiur-radarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-3d-kopiur-grant-identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: radarr-3d-kopiur-grant-identity
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PGUSER: '{{ .PG_BACKUP_USER }}'
        PGPASSWORD: '{{ .PG_BACKUP_PASSWORD }}'
  dataFrom:
  - extract:
      key: kopiur-radarr-3d
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-kopiur-grant-identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: sonarr-kopiur-grant-identity
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PGUSER: '{{ .PG_BACKUP_USER }}'
        PGPASSWORD: '{{ .PG_BACKUP_PASSWORD }}'
  dataFrom:
  - extract:
      key: kopiur-sonarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: whisparr-kopiur-grant-identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: whisparr-kopiur-grant-identity
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      mergePolicy: Replace
      data:
        PGUSER: '{{ .PG_BACKUP_USER }}'
        PGPASSWORD: '{{ .PG_BACKUP_PASSWORD }}'
  dataFrom:
  - extract:
      key: kopiur-whisparr
