apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./externalsecrets.yaml
- ./jobs.yaml
configMapGenerator:
- name: kopiur-backup-identity-grants
  files:
  - provision.sql
  - bazarr.sql
