# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: open-webui-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OPENAI_API_KEYS: "{{ .API_SERVER_KEY }}"
        WEBUI_SECRET_KEY: "{{ .WEBUI_SECRET_KEY }}"
  dataFrom:
  - extract:
      key: open-webui
