# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  annotations:
    oci.home.arpa/allow-rollout: "true"
  name: rook-ceph-cluster
spec:
  interval: 30m
  url: oci://ghcr.io/rook/rook-ceph-cluster
  ref:
    tag: v1.20.1
    digest: sha256:13804d5126727b70f1be40512dbd9b31253569195721a46207f655a5b2917502
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
