# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: op
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: onepassword-connect
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  postRenderers:
  - kustomize:
      images:
      - name: docker.io/1password/connect-api
        digest: sha256:656e4b10df83ca258d8a75b2a051f7c06dd608212f8ae5ba4722e3fe164099d3
      - name: docker.io/1password/connect-sync
        digest: sha256:a760350c941a3e7c98dd66394e9fc3c7e68b6a0a2246a837c74084e534f75f6b
  values:
    connect:
      podAnnotations:
        descheduler.alpha.kubernetes.io/prefer-no-eviction: "true"
      pdb:
        enabled: true
        maxUnavailable: 1
