apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
spec:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
  persistence:
    storageClassName: ceph-block
    storage: 5Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      collect_statistics_interval = 10000
      disk_free_limit.absolute = 1GB
