# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rabbitmq-firecrawl-user
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: rabbitmq-firecrawl-user
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .RABBITMQ_FIRECRAWL_USER }}"
        password: "{{ .RABBITMQ_FIRECRAWL_PASS }}"
  dataFrom:
  - extract:
      key: rabbitmq
