apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: plane
spec:
  name: plane
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: firecrawl
spec:
  name: firecrawl
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: plane
spec:
  importCredentialsSecret:
    name: rabbitmq-plane-user
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: firecrawl
spec:
  importCredentialsSecret:
    name: rabbitmq-firecrawl-user
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: plane
spec:
  vhost: plane
  user: plane
  permissions:
    configure: ".*"
    write: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: firecrawl
spec:
  vhost: firecrawl
  user: firecrawl
  permissions:
    configure: ".*"
    write: ".*"
    read: ".*"
  rabbitmqClusterReference:
    name: rabbitmq
