# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app palworld-rcon
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      palworld-rcon:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/maudecode/palworld-rcon
              tag: main@sha256:7a934c5e3e336501d03e95713b6cd6892198213859f0637dded51fac536623f6
            env:
              RCON_HOST: palworld-rcon-server
              RCON_PORT: "25575"
              RCON_TIMEOUT: "3"
              TZ: ${TIMEZONE}
            envFrom:
            - secretRef:
                name: palworld-rcon-secret
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  initialDelaySeconds: 5
                  periodSeconds: 30
                  timeoutSeconds: 3
                  failureThreshold: 3
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: {drop: ["ALL"]}
              readOnlyRootFilesystem: true
            resources:
              requests:
                cpu: 25m
                memory: 64Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile: {type: RuntimeDefault}
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${HOME_DOMAIN}
        className: internal
        hosts:
        - host: palworld-rcon.${HOME_DOMAIN}
          paths:
          - path: /
            pathType: Prefix
            service:
              identifier: app
              port: http
