# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  annotations:
    oci.home.arpa/allow-rollout: "true"
  name: kube-prometheus-stack
spec:
  interval: 30m
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  ref:
    tag: 88.3.0
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
