# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seafile
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: seafile-secret
    template:
      engineVersion: v2
      data:
        INIT_SEAFILE_ADMIN_EMAIL: "{{ .INIT_SEAFILE_ADMIN_EMAIL }}"
        INIT_SEAFILE_ADMIN_PASSWORD: "{{ .INIT_SEAFILE_ADMIN_PASSWORD }}"
        INIT_SEAFILE_MYSQL_ROOT_PASSWORD: "{{ .MARIADB_ROOT_PASSWORD }}"
        JWT_PRIVATE_KEY: "{{ .JWT_PRIVATE_KEY }}"
        ONLYOFFICE_JWT_SECRET: "{{ .ONLYOFFICE_JWT_SECRET }}"
        SEAFILE_MYSQL_DB_PASSWORD: "{{ .SEAFILE_MYSQL_DB_PASSWORD }}"
  dataFrom:
  - extract:
      key: seafile
