[tools]
actionlint = "1.7.12"
kubectl = "1.36.3"
sops = "3.13.3"
age = "1.3.1"
task = "3.52.0"
flux2 = "2.9.3"
helm = "4.2.3"
jq = "1.8.2"
python = "3.14.7"
"github:budimanjojo/talhelper" = "3.1.16"
"github:home-operations/flate" = "0.4.12"
"github:home-operations/yayamlls" = "0.2.0"
talosctl = "1.13.8"
krew = "0.5.0"
"npm:renovate" = { version = "44.14.3", trust_policy_excludes = ["@yarnpkg/libzip@3.2.2"] }
shellcheck = "0.11.0"
zizmor = "1.29.0"
"asdf:sudermanjr/asdf-yq" = "4.53.3"
crane = "0.21.9"
kyverno = "1.18.2"

[env]
KUBECONFIG = "{{config_root}}/kubernetes/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
K8S_AUTH_KUBECONFIG = "{{config_root}}/kubernetes/kubeconfig"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"
