# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  KUBERNETES_DIR: "{{.ROOT_DIR}}/kubernetes"

includes:
  github: .taskfiles/Github
  kubernetes: .taskfiles/Kubernetes
  talos: .taskfiles/Talos
  # rook: .taskfiles/rook

tasks:

  default: task -l
