apiVersion: v1
kind: Secret
metadata:
    name: tubearchivist-secret
type: Opaque
stringData:
    TA_USERNAME: ENC[AES256_GCM,data:p1KT9a7JamUJj8qmmQ==,iv:+qmUeqCMRwAgHfJUsIyc8MpcLkIMmQZgDEXteb+8+gE=,tag:SpvdVjL2Ezs3r5UmYFFbmA==,type:str]
    TA_PASSWORD: ENC[AES256_GCM,data:DZS6HL1GZlWLSdmNY/CnZUEe+ikBZjHANtYJjhymiBnmoE9akct0wEAUQiV68Qve,iv:Mw5y+5bOp2hXv6C5dOFQxatnga54TaCfjI/586ZIcls=,tag:89i43tdqjjeObtICDf3Mlg==,type:str]
    ELASTIC_PASSWORD: ENC[AES256_GCM,data:9G1WawJ1Yz0zzDgUlpZY2VJ30MPrl4ezsDZVZSBCFgFWMI/fCmXxtqzVB/lNiWkI,iv:jPu/+cpmnVd8OHXxrFlPIWsE5j177/urHYut7fv02Io=,tag:vkjseHcwxZxWmuR462hTWw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySFVMMnUyRUJRZ3NwRktE
            bHdBbEt4eGNtUXkwaXlGR1pkekxVRlpEcG44CndHdXlpa241cElvL0hIWmJ4ZDVo
            RzVsTWl1bmRHNm1vSmk5MFg4NFRtYUkKLS0tIHhoSlZ6dXJYc1l6dVo4cEtrVnFB
            ZFdGclRPVDErMDIzTWtDdFNpZktEZ0EKDHa/PBf29blTiJ2YovDBR3Km1xnOEdxO
            Rq4vjFmrKjjl1mNhq2bhBXfc4uXe0cDMoi3RP/METt15gaVjZu23uA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T04:23:30Z"
    mac: ENC[AES256_GCM,data:Gh7GPt17rDgjmrkLctBj6sWsfwjlESKnSt9/CNufgvc/dKvzG2KaN11te4Qvhec6ETt2yVBWQTJtb049SxeLKshPoLRZCEdMG2mpdR4LuJOf5L2E7MrfcHDjY+7E7pqp8gGjSFm5ZXERsXLqGuHMNDK1th1zJyILSVpX5hhGSfA=,iv:0qXTWYiIxZtVh5yJgblCcDHiULJqdQs8sWskKHBE95I=,tag:/0BYb+qyh7uSRqEwYZe3EA==,type:str]
    version: 3.13.1
