# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: documenso
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: documenso-secret
    template:
      engineVersion: v2
      data:
        NEXTAUTH_SECRET: "{{ .NEXTAUTH_SECRET }}"
        NEXT_PRIVATE_ENCRYPTION_KEY: "{{ .NEXT_PRIVATE_ENCRYPTION_KEY }}"
        NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY: "{{ .NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY }}"
        NEXT_PRIVATE_SIGNING_PASSPHRASE: "{{ .NEXT_PRIVATE_SIGNING_PASSPHRASE }}"
        NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS: "{{ .NEXT_PRIVATE_SIGNING_LOCAL_FILE_CONTENTS }}"
        NEXT_PRIVATE_SMTP_FROM_ADDRESS: "{{ .NEXT_PRIVATE_SMTP_FROM_ADDRESS }}"
        NEXT_PRIVATE_SMTP_FROM_NAME: "{{ .NEXT_PRIVATE_SMTP_FROM_NAME }}"
        NEXT_PRIVATE_DATABASE_URL: >-
          postgres://{{ .DOCUMENSO_POSTGRES_USER }}:{{ .DOCUMENSO_POSTGRES_PASS }}@postgres17-pooler.database.svc.cluster.local:5432/documenso?sslmode=disable
        NEXT_PRIVATE_DIRECT_DATABASE_URL: >-
          postgres://{{ .DOCUMENSO_POSTGRES_USER }}:{{ .DOCUMENSO_POSTGRES_PASS }}@postgres17-rw.database.svc.cluster.local:5432/documenso?sslmode=disable
        INIT_POSTGRES_DBNAME: documenso
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .DOCUMENSO_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .DOCUMENSO_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: documenso
  - extract:
      key: cloudnative-pg
