# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: documenso-envoy
  annotations:
    homepage.shamubernetes.com/enabled: "true"
    homepage.shamubernetes.com/name: "Documenso"
    homepage.shamubernetes.com/description: "Prepare and sign documents"
    homepage.shamubernetes.com/group: "Tools"
    homepage.shamubernetes.com/order: "60"
    homepage.shamubernetes.com/favorite: "false"
    homepage.shamubernetes.com/icon: "dashboard-icons:documenso"
spec:
  parentRefs:
  - name: envoy-internal
    namespace: network
    sectionName: https
  hostnames:
  - "documenso.${HOME_DOMAIN}"
  rules:
  -
    backendRefs:
    - name: documenso
      port: 3000
