# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chaptarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: chaptarr-secret
    template:
      engineVersion: v2
      data:
        CHAPTARR__AUTH__APIKEY: "{{ .CHAPTARR_API_KEY }}"
        CHAPTARR__POSTGRES__HOST: &dbHost postgres17-pooler.database.svc.cluster.local
        CHAPTARR__POSTGRES__PORT: "5432"
        CHAPTARR__POSTGRES__USER: &dbUser "{{ .CHAPTARR_POSTGRES_USER }}"
        CHAPTARR__POSTGRES__PASSWORD: &dbPass "{{ .CHAPTARR_POSTGRES_PASSWORD }}"
        CHAPTARR__POSTGRES__MAINDB: chaptarr_main
        CHAPTARR__POSTGRES__LOGDB: chaptarr_log
        CHAPTARR__POSTGRES__CACHEDB: chaptarr_cache
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: chaptarr
  - extract:
      key: cloudnative-pg
