apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret
type: Opaque
stringData:
    SEARXNG_SECRET: ENC[AES256_GCM,data:VgVU0Drk38XeCGl+ZT6mVR60E9Mc4Wup7KNOldrfAuqp0WFBpChSyPNXUChOjGdq23tCpz9OAaBtsIfEuem54g==,iv:A1+IPoTGrGV77Y+Swo+l/i2Qaai9TFnQyb51feuiXOY=,tag:8kBKU7O1zZgVMe+9Xp5Znw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrQUxFam1icmUwVUU1d0tV
            S1ViZlc3aHo3VGZTelBTc1NvaUcvTXBqZEQ4CjVDeEs1dHphaW9VUE5DNW1zTGJN
            SHBERzROeUFrTHlOOTJCWkVxaWJ1MWMKLS0tIDBQdUtRczNCb2xFMmozWmJSdnhN
            eDdFT2F0VWhGcHBobDBqS1VtcUxvMDQK/WCW2SLIPPtK9vGYAXfzfHR77LSo4NXm
            3HI8n2qbBqIU77TOvU8ghygWXgK54gjTbaP0S6SCHSvHYDrbwozdYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T21:06:31Z"
    mac: ENC[AES256_GCM,data:4f3Gf8mx5kr/hc1mReA1SF2/zpcNiYig03VBRnYre+3An4qVtnFSOucclw3OWyCoIH1FG2XkujeSyw8j+z8p1wDGbopabZcFIjIdKuZvdwDx7QwA0/3EO/lA/g5ZW3jAEUhZdMQ2RuNx51JkEpa5hQu9ayueSOIiAsJnDN2BH5w=,iv:05s8i0B7rNnIkLaZVtEiXhllqDOUnOV1N/YQPqoRGfY=,tag:SxjNUj8Y+W5lWWGPdDJCHQ==,type:str]
    version: 3.13.1
