# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  annotations:
    oci.home.arpa/allow-rollout: "true"
  name: coredns
spec:
  interval: 30m
  url: oci://ghcr.io/coredns/charts/coredns
  ref:
    tag: 1.47.0
    digest: sha256:8e2504e924d3798d181004dc51e10c1c5888c8d5da8a230129e9001a55c37c42
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
