# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onlyoffice
spec:
  interval: 10m
  chart:
    spec:
      chart: app-template
      version: 4.6.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      onlyoffice:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/onlyoffice/documentserver
              tag: 9.4.0.1@sha256:8c114db7648a1654828d33e1f9f3b18e97c4caae6707d34bf04d793d260f7e67
            env:
              JWT_ENABLED: "true"
              JWT_HEADER: Authorization
              JWT_IN_BODY: "false"
              ALLOW_PRIVATE_IP_ADDRESS: "true"
              USE_UNAUTHORIZED_STORAGE: "true"
            envFrom:
            - secretRef:
                name: onlyoffice-secret
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthcheck
                    port: &port 80
                  periodSeconds: 10
                  failureThreshold: 60
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthcheck
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 6
              readiness: *probe
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
              limits:
                memory: 4Gi
    service:
      app:
        controller: onlyoffice
        ports:
          http:
            port: *port
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.${HOME_DOMAIN}
          nginx.ingress.kubernetes.io/proxy-body-size: 100m
        className: internal
        hosts:
        - host: onlyoffice.${HOME_DOMAIN}
          paths:
          - path: /
            service:
              identifier: app
              port: http
    persistence:
      data:
        type: emptyDir
        globalMounts:
        - path: /var/www/onlyoffice/Data
      logs:
        type: emptyDir
        globalMounts:
        - path: /var/log/onlyoffice
