# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: zoo-operator
spec:
  interval: 15m
  secretRef:
    name: ghcr-pull-secret
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:446c748519506303ea94b8238af4a2b41c67deb003550fda981c0c10204dc4b6
  url: oci://ghcr.io/thezoo-house/charts/zoo-operator
