# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: zoo-operator
spec:
  interval: 15m
  secretRef:
    name: ghcr-pull-secret
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:9eeeb14914c462e8dcf8c441689766598824acc3247221fd740b1ae1c693e5bb
  url: oci://ghcr.io/thezoo-house/charts/zoo-operator
