# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firecrawl
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: firecrawl-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        BULL_AUTH_KEY: "{{ .BULL_AUTH_KEY }}"
        REDIS_URL: redis://dragonfly.database.svc.cluster.local:6379/13
        REDIS_RATE_LIMIT_URL: redis://dragonfly.database.svc.cluster.local:6379/14
        NUQ_DATABASE_URL: |-
          postgresql://{{ .FIRECRAWL_POSTGRES_USER }}:{{ .FIRECRAWL_POSTGRES_PASS }}@postgres17-pooler.database.svc.cluster.local:5432/firecrawl_nuq?sslmode=disable
        NUQ_DATABASE_URL_LISTEN: |-
          postgresql://{{ .FIRECRAWL_POSTGRES_USER }}:{{ .FIRECRAWL_POSTGRES_PASS }}@postgres17-pooler.database.svc.cluster.local:5432/firecrawl_nuq?sslmode=disable
        NUQ_RABBITMQ_URL: |-
          amqp://{{ .RABBITMQ_FIRECRAWL_USER }}:{{ .RABBITMQ_FIRECRAWL_PASS }}@rabbitmq.database.svc.cluster.local:5672/firecrawl
        INIT_POSTGRES_DBNAME: firecrawl_nuq
        INIT_POSTGRES_HOST: postgres17-pooler.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .FIRECRAWL_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .FIRECRAWL_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: firecrawl
  - extract:
      key: rabbitmq
  - extract:
      key: cloudnative-pg
