apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-operator-crds
  namespace: observability
spec:
  interval: 30m
  url: oci://ghcr.io/prometheus-community/charts/prometheus-operator-crds
  ref:
    tag: 30.0.1
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
