# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-3d-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: radarr-3d-oidc-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: client-id
    remoteRef:
      key: radarr-3d-oidc
      property: client-id
  - secretKey: client-secret
    remoteRef:
      key: radarr-3d-oidc
      property: client-secret
