# yaml-language-server: $schema=https://k8s-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: radarr-3d-envoy-browser
  annotations:
    homepage.shamubernetes.com/enabled: "true"
    homepage.shamubernetes.com/name: "Radarr 3D"
    homepage.shamubernetes.com/description: "Manage 3D movie downloads"
    homepage.shamubernetes.com/group: "Downloads"
    homepage.shamubernetes.com/order: "30"
    homepage.shamubernetes.com/favorite: "false"
    homepage.shamubernetes.com/icon: "dashboard-icons:radarr"
spec:
  hostnames:
  - radarr-3d.${HOME_DOMAIN}
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-internal
    namespace: network
    sectionName: https
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        remove:
        - Authorization
        - X-Auth-Request-User
        - X-Auth-Request-Email
        - X-Auth-Request-Groups
    backendRefs:
    - group: ""
      kind: Service
      name: radarr-3d
      port: 80
