# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./ocirepository.yaml
- ./externalsecret.yaml
- ./externalsecret-oidc.yaml
- ../../../../templates/volsync
- ./helmrelease.yaml
- ./httproute-envoy-api.yaml
- ./httproute-envoy-browser.yaml
- ./securitypolicy-oidc.yaml
- ./service-envoy-dns.yaml
- ../../../../templates/gatus/guarded
configMapGenerator:
- name: radarr-3d-configmap
  files:
  - pushover-notify.sh=./resources/pushover-notify.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
