# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-nas-repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: kopiur-nas-repository
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        KOPIA_PASSWORD: "{{ .NAS_KOPIA_PASSWORD }}"
  dataFrom:
  - extract:
      key: kopiur-canary
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-r2-repository
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: kopiur-r2-repository
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .VOLSYNC_R2_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .VOLSYNC_R2_SECRET_ACCESS_KEY }}"
        KOPIA_PASSWORD: "{{ .R2_KOPIA_PASSWORD }}"
  dataFrom:
  - extract:
      key: volsync-template
  - extract:
      key: kopiur-canary
