# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./atuin/ks.yaml
- ./changedetection/ks.yaml
- ./convex/ks.yaml
- ./cs2/ks.yaml
- ./cowtail/ks.yaml
- ./git-mirror-operator/ks.yaml
- ./n8n-operator/ks.yaml
- ./onlyoffice/ks.yaml
- ./plane/ks.yaml
- ./plane-github-bridge/ks.yaml
- ./seafile/ks.yaml
- ./static-webserver/ks.yaml
