---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: n8n-operator
  namespace: services
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: n8n-operator
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: n8n-operator-controller-manager
            patch: |-
              - op: add
                path: /spec/template/metadata/labels/app.kubernetes.io~1name
                value: n8n-operator
  values:
    manager:
      image:
        repository: ghcr.io/shamubernetes/n8n-operator
        tag: 0.13.1@sha256:9304481a0144aad2e5ac9ceb4a6afe9bcb10d33160ba04d464e96d15397b981a
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          cpu: 500m
          memory: 512Mi
    crd:
      enable: true
      keep: true
    metrics:
      enable: true
    prometheus:
      enable: true
