# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate-github-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: konflate-github-app
  data:
  - secretKey: KONFLATE_APP_CLIENT_ID
    remoteRef:
      key: Konflate GitHub App
      property: APP_CLIENT_ID
  - secretKey: KONFLATE_APP_PRIVATE_KEY
    remoteRef:
      key: Konflate GitHub App
      property: APP_PRIVATE_KEY
  - secretKey: KONFLATE_WEBHOOK_SECRET
    remoteRef:
      key: Konflate GitHub App
      property: WEBHOOK_SECRET
