# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: konflate-envoy
  annotations:
    homepage.shamubernetes.com/enabled: "true"
    homepage.shamubernetes.com/name: "Konflate"
    homepage.shamubernetes.com/description: "Review rendered pull request changes"
    homepage.shamubernetes.com/group: "Infrastructure"
    homepage.shamubernetes.com/order: "30"
    homepage.shamubernetes.com/favorite: "false"
spec:
  parentRefs:
  - name: envoy-internal
    namespace: network
    sectionName: https
  hostnames:
  - "konflate.${HOME_DOMAIN}"
  rules:
  -
    backendRefs:
    - name: konflate
      port: 8080
