apiVersion: v1
kind: Service
metadata:
  name: listenarr-envoy-dns
  annotations:
    external-dns.alpha.kubernetes.io/hostname: listenarr.${HOME_DOMAIN}
    external-dns.alpha.kubernetes.io/target: ${IPAM_IP_ENVOY_INTERNAL}
spec:
  type: ExternalName
  externalName: envoy-internal.network.svc.cluster.local
