# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-app
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: plane-app-secret
    template:
      engineVersion: v2
      data:
        SECRET_KEY: "{{ .PLANE_SECRET_KEY }}"
        LIVE_SERVER_SECRET_KEY: "{{ .PLANE_LIVE_SERVER_SECRET_KEY }}"
        GITHUB_CLIENT_ID: "{{ .PLANE_GITHUB_CLIENT_ID }}"
        GITHUB_CLIENT_SECRET: "{{ .PLANE_GITHUB_CLIENT_SECRET }}"
        GITHUB_ORGANIZATION_ID: "{{ .PLANE_GITHUB_ORG_ID }}"
        ENABLE_GITHUB_SYNC: "1"
        IS_GITHUB_ENABLED: "1"
        REDIS_URL: redis://dragonfly.database.svc.cluster.local:6379/12
        DATABASE_URL: |-
          postgresql://{{ .PLANE_POSTGRES_USER }}:{{ .PLANE_POSTGRES_PASS }}@postgres17-pooler.database.svc.cluster.local:5432/plane?sslmode=disable
        AMQP_URL: |-
          amqp://{{ .PLANE_RABBITMQ_USER }}:{{ .PLANE_RABBITMQ_PASS }}@plane-rabbitmq.services.svc.cluster.local:5672/
        INIT_POSTGRES_DBNAME: plane
        INIT_POSTGRES_HOST: postgres17-pooler.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .PLANE_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .PLANE_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: plane
  - extract:
      key: cloudnative-pg
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-live
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: plane-live-secret
    template:
      engineVersion: v2
      data:
        LIVE_SERVER_SECRET_KEY: "{{ .PLANE_LIVE_SERVER_SECRET_KEY }}"
        REDIS_URL: redis://dragonfly.database.svc.cluster.local:6379/12
  dataFrom:
  - extract:
      key: plane
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-rabbitmq
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: plane-rabbitmq-secret
    template:
      engineVersion: v2
      data:
        RABBITMQ_DEFAULT_USER: "{{ .PLANE_RABBITMQ_USER }}"
        RABBITMQ_DEFAULT_PASS: "{{ .PLANE_RABBITMQ_PASS }}"
  dataFrom:
  - extract:
      key: plane
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: plane-doc-store
spec:
  target:
    name: plane-doc-store-secret
    template:
      engineVersion: v2
      data:
        FILE_SIZE_LIMIT: "5242880"
        AWS_S3_BUCKET_NAME: plane-uploads
        USE_MINIO: "0"
        AWS_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY }}"
        AWS_SECRET_ACCESS_KEY: "{{ .S3_SECRET_KEY }}"
        AWS_S3_ENDPOINT_URL: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc.cluster.local:80
        AWS_REGION: us-east-1
  dataFrom:
  - extract:
      key: rook-ceph-object-user-ceph-objectstore-plane
    rewrite:
    - regexp:
        source: "AccessKey"
        target: "S3_ACCESS_KEY"
    - regexp:
        source: "SecretKey"
        target: "S3_SECRET_KEY"
    sourceRef:
      storeRef:
        kind: ClusterSecretStore
        name: rook-ceph-secrets
