# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: hubble-ui-envoy
  annotations:
    homepage.shamubernetes.com/enabled: "true"
    homepage.shamubernetes.com/name: "Hubble"
    homepage.shamubernetes.com/description: "Inspect cluster network flows"
    homepage.shamubernetes.com/group: "Observability"
    homepage.shamubernetes.com/order: "60"
    homepage.shamubernetes.com/favorite: "false"
    homepage.shamubernetes.com/icon: "selfhst:cilium-hubble"
spec:
  parentRefs:
  - name: envoy-internal
    namespace: network
    sectionName: https
  hostnames:
  - "hubble.${HOME_DOMAIN}"
  rules:
  - backendRefs:
    - name: hubble-ui
      port: 80
