---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-credential-imap-maude
  namespace: services
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: n8n-credential-imap-maude
    template:
      engineVersion: v2
      data:
        password: "{{ .AppPassword }}"
  dataFrom:
    - extract:
        key: maude-smtp
---
apiVersion: n8n.n8n.io/v1alpha1
kind: N8nCredential
metadata:
  name: imap-maude
  namespace: services
spec:
  n8nInstance:
    serviceRef:
      name: n8n
      namespace: services
      port: 5678
    apiKeySecretRef:
      name: n8n-api-key
      key: api-key
  credentialName: "IMAP Maude Mail"
  credentialType: "imap"
  deletionPolicy: Retain
  secretRef:
    name: n8n-credential-imap-maude
  data:
    host: "imap.fastmail.com"
    port: "993"
    secure: "true"
    allowUnauthorizedCerts: "false"
    user: "maude@maudeco.de"
  fieldMappings:
    password: password
