# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    deployment:
      envoyGateway:
        image:
          repository: docker.io/envoyproxy/gateway
          # renovate: datasource=docker depName=docker.io/envoyproxy/gateway
          tag: v1.9.2@sha256:9d67017c442a70e6ae9f1a358e6c80eb653c67c2e40823d9a991e0daf37ba926
    config:
      envoyGateway:
        provider:
          type: Kubernetes
          kubernetes:
            leaderElection:
              leaseDuration: 30s
              renewDeadline: 20s
              retryPeriod: 5s
            deploy:
              type: GatewayNamespace
        logging:
          level:
            default: info
