# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    deployment:
      envoyGateway:
        image:
          repository: docker.io/envoyproxy/gateway
          # renovate: datasource=docker depName=docker.io/envoyproxy/gateway
          tag: v1.8.3@sha256:e7a8c70537628bf996e5dec5c4c835704b4b9f4f715a74cf361bea30608c49ac
    config:
      envoyGateway:
        provider:
          type: Kubernetes
          kubernetes:
            leaderElection:
              leaseDuration: 30s
              renewDeadline: 20s
              retryPeriod: 5s
            deploy:
              type: GatewayNamespace
        logging:
          level:
            default: info
