apiVersion: v1
kind: Secret
metadata:
    name: grimmory-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:f1o/UZO5ZrunO735Ffhquv3WWmq4W5HuPsgonSDvr5lTwf5RTG8=,iv:YTfoVJMgCg5Fwgx7kdH2+SN3/xXPPqtn8eUMDCHfvls=,tag:ZwdLeeTFbB4bjtvkfsZxKA==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:MybMNKtEfq8=,iv:41rdFVe/nR1wD1C1rG70h2ZciFByuFUkSOsF8n1sn4g=,tag:n0T8gU3ZN7FRpiR9myVXLQ==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:ytHZ0eXBvQd/EcVEtpMGPnXS7Kw2EvwVbgdLPwdyrl47gAXWUlZKO8isnq4Hr1IN,iv:qBsJWrreaYjyYJNuKimIFespapVi8VSzZ0jIbiWaBVc=,tag:/w3+pDO+AqMPAhscU3UIkA==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:pc+yPRJZw5FoplafXpxgodliuokTwDNcj9gCByE6935ONcWEs+EIIwYFtmEjZKXU,iv:or7Xeg9+DGPvs3wWcok4PyAiAY/Y/6ogBI7lMxZLCm4=,tag:mctzhnMcw3iglOsoCLQOqA==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:NHuymgJT+HY=,iv:dvpT/UQog2tI6A9tIhEwpSG6L8m3keUDbppuEZYHnqc=,tag:C1XT0er0kZjquroUlr+EGw==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:ZIFLcy6M5dM=,iv:dGDk9zH3y1Ndtl0UbVuTSFQFm/pio6taeBQL1rGCutw=,tag:ph5TGem96eWD1b3WntttBQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:rpV77k8b1leXdBVez86/xfmwxheJZ9NKHsp+QKazk/+k3SGEp1hERop92LSMlwX/,iv:UUZfWl4x3yNNenwHQknwHgjj+2NeLQsth2vGQxaylG0=,tag:goeMUosHr3tIUzXrNx15Eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5d0lsSWNuVC9NM0hsKzIw
            YmlPRUtqR3RCSkVpL2FaL0dFNEJsZW81ejJvCkNKSnNzZjcwN3NxU0tVaU5qYWlD
            ckhGZnJhU2pyVk9KM1lMdWZ6d1lHV3cKLS0tIEFVR0xPY1dCcmZva1B1U1grekVE
            OU16cW5FdWJqNXV4S3RHT1NzVHVTYjgKjex4QWmzjxFbin2RbP+L9OYw420qDfuR
            chgwsZIop7qfVqSBn4AZ1l6RikPeRqrlTH77FSQePrmoFOvzyivj6g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T13:35:19Z"
    mac: ENC[AES256_GCM,data:3e7OiFGSdworIZCNxRSdL0bi9X5x1uiQ+5BrwkNhl0FmfPonmmFE1wIOrbTjuSh8oH4zdMFlvLLuo4rOJq/vFfDgXn5LpEyv5hDPgAAEpTED3bMZQvmYnvUMu3Bi1JbaD916AZNZAVzKZeHXiXjzrtsSZrxRtQBS0fSfGmQiASU=,iv:3L2BXscqXiZr3qd56E5p9AQbZ+rA75vC3wFUyu9eQgU=,tag:uzTyqp8Rtw3wZH+VRZS/+Q==,type:str]
    version: 3.13.1
