apiVersion: v1
kind: Secret
metadata:
    name: grimmory-secret
type: Opaque
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:/u9qHmehO8PClnQW1zGsSJUEJGkjGmlcWj7O0NNEe+ZdsKZwkgInhQx5HJ7rzgcd70d+8MVE5JG4+EuAQRbWpyS30SnY,iv:XV8I9raJWtOqsAXHiHiUuYZQ+rzJVPqgguhHR4tgSXQ=,tag:H+s9NmpWYPKIzfC6NKJy3g==,type:str]
    DATABASE_USERNAME: ENC[AES256_GCM,data:SLTEHaWVTO8=,iv:WGkAI5nbV2mKluurvsoIFmhFcHY81Gh3oLlYsFyTVqE=,tag:iEv07+LR6GQLjzF2nLKzJA==,type:str]
    DATABASE_PASSWORD: ENC[AES256_GCM,data:SsM50DBAIFCXgy6uVqfWkOnO0+eQ+Yqhb5zTWdhjMBYOpQIroCIkaDy2buB2VmwM,iv:WFuS6+Z2kM+I0XjGO9Inse/UzTXh+aWbKRnLq1rER8Q=,tag:i7pWnQ0OW+8O9jLOCCAQOg==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:YGpqV3WdkEdBm12lbIpTF1M73YmhRLwpd2T68d31sJxe5sRrnGoozbi5/0t44Te2,iv:KVhnhhW1jf7yXkHNeJsnuP3FgG6Ex2ryzkaS5rBJlbg=,tag:mnWSmRUKNi0bgRJ73stoTQ==,type:str]
    MYSQL_DATABASE: ENC[AES256_GCM,data:OAn4NxKS9K4=,iv:fy0IgAOxCpQabifXx2VvBsSn3OqirQ78BVySxwQD1iA=,tag:tR1dcDkptdO3W0Q9lnunmA==,type:str]
    MYSQL_USER: ENC[AES256_GCM,data:Uh3JpyCDyB4=,iv:ivsa1Gpd/Bh1U+oDh8tvaO/NPa/Nd64u19bEbjFjUlY=,tag:4s29yOMvQnVHzZBngJx2bQ==,type:str]
    MYSQL_PASSWORD: ENC[AES256_GCM,data:vXNEfC7W+iwTNH5hDZvRzo8hGQn0ifa8WYHi934LHxLf8HwroLtFzGMnfhvJu3xL,iv:1n2KAmYLSN5Dsw9ua8+cagdR1a5rzfJq+zoJbsY/x30=,tag:o5BSpPcPhsNTrEunIbUeyA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMnFWeTl2cEpVaVBCOHRm
            eDc4cFZGSG9ucUZXb1VkUmR3Ni8weHlza0JBCi9uQXdyYm5URlRyRTIwNjM0b000
            UXZMcXJybHR5bXRndU1vU1NxeVVPOFkKLS0tIFJyYXlJcUdHVFFLQnU0KzN5bXRv
            d0hwOFErLzBWTDFrU1lDc3lQVFRGU00Kf51L8RsmcAI/4SZS9hY/jrq3S4d+uXen
            0rIS2+Ndxipt5dAz3UulHt3bwPquUXxwg8VMAHN+2+LBniIV3+34EA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T13:26:06Z"
    mac: ENC[AES256_GCM,data:0pg/Rv4KHIl81HjhPpXln7hTbw6bViqLKaFTn1BM1bs7D9eYgR+8AppT1Q+x4wIzGJjakDcvitBv4w512yS5/fZC4jKhWf/R4p95FYt2SMghp+uSEEomP1dDmwap8U8vuXwQbJIHI4wT4wYzk/UuamO8K9bTqJ3Ucv3BlMeUJZY=,iv:+6z/u6qBuKJT7w/rFv2UzjYb7Aj4VXsHWGyF6MdnI7M=,tag:elyhsxfX9b1SS0PcBzYK6Q==,type:str]
    version: 3.13.1
