collections:
  Kids Movies:
    radarr_taglist:
    - kids
    smart_label: title.asc
    item_label:
    - Kids
    non_item_remove_label:
    - Kids
    sort_title: "!001_Kids Movies"
    collection_mode: hide
