# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: romm-envoy
  annotations:
    homepage.shamubernetes.com/enabled: "true"
    homepage.shamubernetes.com/name: "RomM"
    homepage.shamubernetes.com/description: "Browse and play the retro game library"
    homepage.shamubernetes.com/group: "Games"
    homepage.shamubernetes.com/order: "10"
    homepage.shamubernetes.com/favorite: "false"
    homepage.shamubernetes.com/icon: "dashboard-icons:romm"
spec:
  parentRefs:
  - name: envoy-internal
    namespace: network
    sectionName: https
  hostnames:
  - "romm.${HOME_DOMAIN}"
  rules:
  - backendRefs:
    - name: romm
      port: 8080
