# yaml-language-server: $schema=https://k8s-schemas.pages.dev/v1/serviceaccount.json
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oceanus-drain-recovery
  namespace: system-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oceanus-drain-recovery
rules:
- apiGroups: [""]
  resources: [nodes]
  resourceNames: [k8s-oceanus]
  verbs: [get, patch]
- apiGroups: [tuppr.home-operations.com]
  resources: [talosupgrades]
  resourceNames: [talos]
  verbs: [get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: oceanus-drain-recovery
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: oceanus-drain-recovery
subjects:
- kind: ServiceAccount
  name: oceanus-drain-recovery
  namespace: system-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oceanus-drain-recovery
  namespace: system-upgrade
rules:
- apiGroups: [batch]
  resources: [jobs]
  verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oceanus-drain-recovery
  namespace: system-upgrade
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oceanus-drain-recovery
subjects:
- kind: ServiceAccount
  name: oceanus-drain-recovery
  namespace: system-upgrade
