per_listener_settings false

listener 1883
protocol mqtt
allow_anonymous false

listener 8883
protocol mqtt
allow_anonymous false

certfile /mosquitto/tls/tls.crt
keyfile /mosquitto/tls/tls.key
tls_version tlsv1.2

plugin /usr/lib/mosquitto_dynamic_security.so
plugin_opt_config_file /mosquitto/data/dynamic-security.json

persistence true
persistence_location /mosquitto/data/
autosave_interval 60
autosave_on_changes true

log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true
