# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitmirror-github-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: gitmirror-github-app
    template:
      engineVersion: v2
      data:
        app-id: "{{ .github_app_id }}"
        installation-id: "{{ .github_app_installation_id }}"
        private-key.pem: "{{ .github_app_private_key }}"
        webhook-secret: "{{ .github_app_webhook_secret }}"
  data:
  - secretKey: github_app_id
    remoteRef:
      key: Shamubernetes Git Mirror
      property: App ID
  - secretKey: github_app_installation_id
    remoteRef:
      key: Shamubernetes Git Mirror
      property: Installation ID
  - secretKey: github_app_private_key
    remoteRef:
      key: Shamubernetes Git Mirror
      property: private-key.pem
  - secretKey: github_app_webhook_secret
    remoteRef:
      key: Shamubernetes Git Mirror
      property: webhook secret

# yamllint disable-line rule:document-start
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitmirror-codeberg-ssh
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: gitmirror-codeberg-ssh
    template:
      engineVersion: v2
      type: kubernetes.io/ssh-auth
      data:
        ssh-privatekey: "{{ .codeberg_private_key }}"
  data:
  - secretKey: codeberg_private_key
    remoteRef:
      key: gitmirror - codeberg external-secrets
      property: private-key.pem
