apiVersion: mirror.shamubernetes.com/v1alpha1
kind: GitMirror
metadata:
  name: home-k8s
spec:
  provider: github
  github:
    owner: shamubernetes
    repo: home-k8s
    webhookSecretRef:
      name: gitmirror-github-app
      key: webhook-secret
  source:
    url: https://github.com/shamubernetes/home-k8s.git
    auth:
      type: githubApp
      githubApp:
        appIDSecretRef:
          name: gitmirror-github-app
          key: app-id
        installationIDSecretRef:
          name: gitmirror-github-app
          key: installation-id
        privateKeySecretRef:
          name: gitmirror-github-app
          key: private-key.pem
  target:
    url: git@codeberg.org:shamubernetes/home-k8s.git
    auth:
      type: ssh
      ssh:
        privateKeyRef:
          name: gitmirror-codeberg-ssh
          key: ssh-privatekey
  mirror:
    mode: exact
  fallback:
    schedule: "17 * * * *"
  job:
    image: ghcr.io/shamubernetes/git-mirror-sync:v0.3.1@sha256:16978854a5d17e1c7f9c8e7a2facf07b6477b5a0a05752f879812c64e7e63a2e
    serviceAccountName: git-mirror-sync
    knownHostsConfigMapName: git-mirror-known-hosts
    knownHostsConfigMapKey: known_hosts
    backoffLimit: 2
    activeDeadlineSeconds: 1800
    ttlSecondsAfterFinished: 3600
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi
