# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: changedetection
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: changedetection-secret
    template:
      engineVersion: v2
      data:
        CHANGEDETECTION_API_TOKEN: "{{ .CHANGEDETECTION_API_TOKEN }}"
        CHANGEDETECTION_NOTIFICATION_URL: "pover://{{ .PUSHOVER_USER_KEY }}@{{ .CHANGEDETECTION_PUSHOVER_TOKEN }}"
  dataFrom:
  - extract:
      key: changedetection
  - extract:
      key: pushover
