# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: grafana-operator
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    namespaceScope: true
    leaderElect: true
    replicas: 2
    image:
      tag: v5.25.0@sha256:bc572995823fcfc32d2e960a47324a87baae8e4c9f821b8564026243e73624f3
    resources:
      requests:
        cpu: 20m
        memory: 96Mi
      limits:
        memory: 256Mi
    serviceMonitor:
      enabled: true
    dashboard:
      enabled: true
