# yaml-language-server: $schema=https://k8s-schemas.pages.dev/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: sonarr-oidc-canary
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: sonarr-oidc-canary-browser
  oidc:
    provider:
      issuer: https://sso.${HOME_DOMAIN}
    clientIDRef:
      group: ""
      kind: Secret
      name: sonarr-oidc-canary-secret
    clientSecret:
      group: ""
      kind: Secret
      name: sonarr-oidc-canary-secret
    redirectURL: https://sonarr-oidc-canary.${HOME_DOMAIN}/oauth2/callback
    logoutPath: /oauth2/logout
    cookieConfig:
      sameSite: Lax
    cookieNames:
      accessToken: sonarr-canary-access-token
      idToken: sonarr-canary-id-token
    forwardAccessToken: false
    passThroughAuthHeader: false
    scopes:
    - openid
    - profile
    - email
