# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: seafile-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: seafile-db-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          k8s.mariadb.com/watch: ""
      data:
        MARIADB_ROOT_PASSWORD: "{{ .MARIADB_ROOT_PASSWORD }}"
        SEAFILE_MYSQL_DB_PASSWORD: "{{ .SEAFILE_MYSQL_DB_PASSWORD }}"
  dataFrom:
  - extract:
      key: seafile
