# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubewings-node
  namespace: services
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: kubewings-node-secret
    template:
      engineVersion: v2
      data:
        KUBEWINGS_NODE_TOKEN: "{{ .NODE_TOKEN }}"
        KUBEWINGS_NODE_TOKEN_ID: "{{ .NODE_TOKEN_ID }}"
  dataFrom:
  - extract:
      key: kubewings
