# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cs2-gamekeeper
  namespace: kubewings-mvp
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: cs2-gamekeeper
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        token: "{{ .TOKEN }}"
  data:
    - secretKey: TOKEN
      remoteRef:
        key: The Zoo - Gamekeeper
        property: CS2_AGENT_TOKEN
