# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  annotations:
    oci.home.arpa/allow-rollout: "true"
  name: victoria-logs-collector
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.3.7
    digest: sha256:2ec5d41cbc0309ef0cfa10945e5b7773298ba25b8a67a28296f888b8adb2b0ba
  url: oci://ghcr.io/victoriametrics/helm-charts/victoria-logs-collector
