# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-kopiur-nas
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: homarr-kopiur-nas
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        KOPIA_PASSWORD: "{{ .NAS_KOPIA_PASSWORD }}"
        KOPIA_RCLONE_CONFIG: |
          [mnemosyne]
          type = smb
          host = ${IPAM_IP_NFS}
          user = guest
          pass =
          domain = WORKGROUP
  dataFrom:
  - extract:
      key: kopiur-homarr
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homarr-kopiur-r2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: homarr-kopiur-r2
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      data:
        AWS_ACCESS_KEY_ID: "{{ .VOLSYNC_R2_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .VOLSYNC_R2_SECRET_ACCESS_KEY }}"
        KOPIA_PASSWORD: "{{ .R2_KOPIA_PASSWORD }}"
  dataFrom:
  - extract:
      key: volsync-template
  - extract:
      key: kopiur-homarr
