# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app homarr
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: homarr
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  dependsOn:
  - name: rook-ceph-cluster
    namespace: rook-ceph
  - name: volsync
    namespace: volsync-system
  values:
    controllers:
      homarr:
        strategy: RollingUpdate
        rollingUpdate:
          surge: "0"
          unavailable: 1
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/homarr-labs/homarr
              tag: v1.76.0@sha256:1a47c2afd892d8939b49195a7098fcbe44f4ac15a74b9ba02ed2de237089542f
            env:
              AUTH_PROVIDERS: credentials
              DB_DIALECT: sqlite
              DB_DRIVER: better-sqlite3
              DB_URL: /appdata/db.sqlite
              ENABLE_DOCKER: "false"
              ENABLE_KUBERNETES: "false"
              PGID: "568"
              PUID: "568"
              TZ: ${TIMEZONE}
            envFrom:
            - secretRef:
                name: homarr-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/health/live
                    port: &port 7575
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 5
              readiness:
                <<: *probes
                custom: true
                spec:
                  httpGet:
                    path: /api/health/ready
                    port: *port
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 2
                  failureThreshold: 5
            securityContext:
              allowPrivilegeEscalation: false
            resources:
              requests:
                cpu: 25m
                memory: 256Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: {type: RuntimeDefault}
    service:
      app:
        controller: *app
        ports:
          http:
            port: *port
    persistence:
      config:
        existingClaim: *app
        globalMounts:
        - path: /appdata
