# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./ocirepository.yaml
- ./externalsecret.yaml
- ./rbac.yaml
- ./helmrelease.yaml
- ./httproute-envoy.yaml

- ../../../../templates/gatus/external
configMapGenerator:
- name: gatus-configmap
  files:
  - config.yaml=./resources/config.yaml
- name: gatus-config-reload
  files:
  - reload-config.sh=./resources/reload-config.sh
generatorOptions:
  disableNameSuffixHash: true
