# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cowbell
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    digest: sha256:ec37f48d0b97617c4997cab64779ae9ff8f5c8af7f22eeb3d9a91998cb570fe4
  secretRef:
    name: ghcr-pull-secret
  url: oci://ghcr.io/maudecode/charts/cowbell
