# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  annotations:
    oci.home.arpa/allow-rollout: "true"
  name: kopiur
spec:
  interval: 30m
  url: oci://ghcr.io/home-operations/charts/kopiur
  ref:
    # renovate: datasource=docker depName=ghcr.io/home-operations/charts/kopiur
    tag: 0.10.1
    digest: sha256:4d6cefa1bad54846d908b58227043facc890d05d6e94465b5724d0f6356dd2be
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
