# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atproto-pds
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: atproto-pds-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PDS_JWT_SECRET: "{{ .PDS_JWT_SECRET }}"
        PDS_ADMIN_PASSWORD: "{{ .PDS_ADMIN_PASSWORD }}"
        PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX: "{{ .PDS_PLC_ROTATION_KEY_K256_PRIVATE_KEY_HEX }}"
  dataFrom:
  - extract:
      key: atproto-pds
