# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kometa
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: kometa-secret
    creationPolicy: Owner
  data:
  - secretKey: KOMETA_PLEX_API_KEY
    remoteRef:
      key: plex
      property: PLEX_TOKEN
  - secretKey: KOMETA_RADARR_API_KEY
    remoteRef:
      key: radarr
      property: RADARR_API_KEY
  - secretKey: KOMETA_SONARR_API_KEY
    remoteRef:
      key: sonarr
      property: SONARR_API_KEY
  - secretKey: KOMETA_TMDB_API_KEY
    remoteRef:
      key: TMDB
      property: TMDB_API_KEY
