# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./ocirepository.yaml
- ../../../../templates/volsync
- ./externalsecret.yaml
- ./helmrelease.yaml
configMapGenerator:
- name: kometa-config
  files:
  - config.yml=./configs/config.yml
  - finn-bootstrap-movies.yml=./configs/finn-bootstrap-movies.yml
  - finn-bootstrap-tv.yml=./configs/finn-bootstrap-tv.yml
  - kids-movies.yml=./configs/kids-movies.yml
  - kids-tv.yml=./configs/kids-tv.yml
generatorOptions:
  disableNameSuffixHash: true
