apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: ghcr-pull-secret
spec:
  externalSecretName: ghcr-pull-secret
  namespaceSelectors:
  - matchExpressions:
    - key: kubernetes.io/metadata.name
      operator: NotIn
      values:
      - cilium-secrets
      - kube-node-lease
      - kube-public
      - kube-system
  refreshTime: 1m
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      kind: ClusterSecretStore
      name: op-secret-store
    target:
      name: ghcr-pull-secret
      creationPolicy: Owner
      template:
        engineVersion: v2
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |
            {"auths":{"ghcr.io":{"username":"{{ .GHCR_USERNAME }}","password":"{{ .GHCR_TOKEN }}","auth":"{{ printf "%s:%s" .GHCR_USERNAME .GHCR_TOKEN | b64enc }}"}}}
    dataFrom:
    - extract:
        key: GitHub Container Registry