# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
spec:
  interval: 30m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: loki
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  postRenderers:
  - kustomize:
      patches:
      - target:
          kind: StatefulSet
          name: loki-backend
        patch: |-
          - op: add
            path: /spec/persistentVolumeClaimRetentionPolicy
            value:
              whenDeleted: Retain
              whenScaled: Retain
      - target:
          kind: StatefulSet
          name: loki-write
        patch: |-
          - op: add
            path: /spec/persistentVolumeClaimRetentionPolicy
            value:
              whenDeleted: Retain
              whenScaled: Retain
  dependsOn:
  - name: openebs
    namespace: openebs-system
  - name: rook-ceph-cluster
    namespace: rook-ceph
  valuesFrom:
  # NOTE: BUCKET_HOST from OBC doesn't include protocol, but Loki requires a valid URI
  # - targetPath: loki.storage.s3.endpoint
  #   kind: ConfigMap
  #   name: *cephBucket
  #   valuesKey: BUCKET_HOST
  - targetPath: loki.storage.s3.region
    kind: ConfigMap
    name: &cephBucket loki-bucket
    valuesKey: BUCKET_REGION
  - targetPath: loki.storage.s3.accessKeyId
    kind: Secret
    name: *cephBucket
    valuesKey: AWS_ACCESS_KEY_ID
  - targetPath: loki.storage.s3.secretAccessKey
    kind: Secret
    name: *cephBucket
    valuesKey: AWS_SECRET_ACCESS_KEY
  values:
    deploymentMode: SimpleScalable
    loki:
      image:
        registry: docker.io
        repository: grafana/loki
        tag: 3.6.11@sha256:44148ad243c07957113baea950ee5ba9b0c8eff8d7e38ff3cc1c0af705790945
      podAnnotations:
        configmap.reloader.stakater.com/reload: *cephBucket
        secret.reloader.stakater.com/reload: *cephBucket
      ingester:
        chunk_encoding: snappy
      storage:
        type: s3
        bucketNames:
          chunks: "loki"
          ruler: "loki"
          admin: "loki"
        s3:
          endpoint: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc:80
          s3ForcePathStyle: true
          insecure: true
      schemaConfig:
        configs:
        - from: "2024-04-01" # quote
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
      structuredConfig:
        auth_enabled: false
        server:
          log_level: info
          http_listen_port: 3100
          grpc_listen_port: 9095
          grpc_server_max_recv_msg_size: 8388608
          grpc_server_max_send_msg_size: 8388608
        limits_config:
          ingestion_burst_size_mb: 128
          ingestion_rate_mb: 64
          max_query_parallelism: 100
          per_stream_rate_limit: 64M
          per_stream_rate_limit_burst: 128M
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          retention_period: 30d
          shard_streams:
            enabled: true
          split_queries_by_interval: 1h
        query_scheduler:
          max_outstanding_requests_per_tenant: 4096
        frontend:
          max_outstanding_per_tenant: 4096
        ruler:
          enable_api: true
          enable_alertmanager_v2: true
          alertmanager_url: http://alertmanager-operated.observability.svc.cluster.local:9093
          storage:
            type: local
            local:
              directory: /rules
          rule_path: /rules/fake
        analytics:
          reporting_enabled: false
    lokiCanary:
      image:
        registry: docker.io
        repository: grafana/loki-canary
        tag: 3.6.11@sha256:9ea589c612c3b01f2f9c3de3fa898f0476b3ba14526950ba4fe8906f50a6af81
    memcached:
      image:
        registry: docker.io
        repository: library/memcached
        tag: 1.6.39-alpine@sha256:c8503d4491edd3110cc07d0465089d3a41cf1daf8645e71149e39a51835e92cd
    memcachedExporter:
      image:
        registry: docker.io
        repository: prom/memcached-exporter
        tag: v0.15.4@sha256:b6763ecb3c47f2408e0398518851b7f8c5fc46232b2649f8c78a321130c54266
    sidecar:
      image:
        registry: docker.io
        repository: kiwigrid/k8s-sidecar
        tag: 2.5.0@sha256:a6b3f707f883108376514489a94d6629109a327b2978e1d826cd104c4ca436df
    backend:
      replicas: 2
      persistence:
        enableStatefulSetAutoDeletePVC: false
        size: 20Gi
        storageClass: openebs-hostpath
      podLabels:
        titans/network-intensive: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  titans/network-intensive: "true"
              topologyKey: kubernetes.io/hostname
    gateway:
      replicas: 2
      image:
        registry: docker.io
        repository: nginxinc/nginx-unprivileged
        tag: 1.31-alpine@sha256:59ccf0943b0b8e8d9e6ea9039a39555730f544701a655c596f7df7d096c593f5
      deploymentStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 0
          maxUnavailable: 1
      podLabels:
        titans/network-intensive: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  titans/network-intensive: "true"
              topologyKey: kubernetes.io/hostname
    read:
      replicas: 2
      podLabels:
        titans/network-intensive: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  titans/network-intensive: "true"
              topologyKey: kubernetes.io/hostname
    write:
      replicas: 2
      persistence:
        enableStatefulSetAutoDeletePVC: false
        size: 20Gi
        storageClass: openebs-hostpath
      podLabels:
        titans/network-intensive: "true"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: DoesNotExist
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchLabels:
                  titans/network-intensive: "true"
              topologyKey: kubernetes.io/hostname
