# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./ocirepository.yaml
- ./helmrelease.yaml
- ./httproute-envoy.yaml
- ./service-envoy-dns.yaml
- ./prometheusrule.yaml
- ./vmalert-deployment.yaml
- ./vmalert-service.yaml
- ./vmalert-podmonitor.yaml
- ./collector
configMapGenerator:
- name: victoria-logs-vmalert-rules
  files:
  - plex.yaml=./resources/vmalert-rules.yaml
