spegel:
  mirroredRegistries:
  - https://docker.io
  additionalMirrorTargets:
  - https://registry-1.docker.io
  containerdSock: /run/containerd/containerd.sock
  containerdRegistryConfigPath: /etc/cri/conf.d/hosts
service:
  registry:
    hostPort: 29999
