# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: cert-manager
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v1.21.1@sha256:416a2d76870d996460e62bd7f521bf14fa017be9e3e904aab92163a331fcb61a
    webhook:
      image:
        repository: quay.io/jetstack/cert-manager-webhook
        tag: v1.21.1@sha256:d8b3961b51c8c7320633f8208dc46bf88aa13804d0f7cbe48a096b2c523cee42
    cainjector:
      image:
        repository: quay.io/jetstack/cert-manager-cainjector
        tag: v1.21.1@sha256:ccf6b919ec0500745a47a910118f834f9636d0aac1ff221245cd2557ed8c7c98
    startupapicheck:
      image:
        repository: quay.io/jetstack/cert-manager-startupapicheck
        tag: v1.21.1@sha256:d8ab6416e6e7303a86fa0a8daa82c94a8001f21c9d78eb2e7db20534e5d07ae8
    installCRDs: true
    dns01RecursiveNameservers: 1.1.1.1:53,9.9.9.9:53
    dns01RecursiveNameserversOnly: true
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
      - "1.1.1.1"
      - "9.9.9.9"
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
