# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: cert-manager
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: quay.io/jetstack/cert-manager-controller
      tag: v1.20.2
      digest: sha256:fe0623d7d04a382c888f03343a3a2da716e0d96ad3d5d790c0ebcbcb2a4329a5
    webhook:
      image:
        repository: quay.io/jetstack/cert-manager-webhook
        tag: v1.20.2
        digest: sha256:baf651128b9f05c426cbd5e60e2036bf382c99ca270f49d0757d6f7d2452f4e5
    cainjector:
      image:
        repository: quay.io/jetstack/cert-manager-cainjector
        tag: v1.20.2
        digest: sha256:6f5a644135887b2aa7d5cc145072fa56421560e3586ff1f184358022d490f4e1
    startupapicheck:
      image:
        repository: quay.io/jetstack/cert-manager-startupapicheck
        tag: v1.20.2
        digest: sha256:4e2a69b4a0cc9627905bbeecf720f95d5153ca39cacdab923d2748e73556792b
    installCRDs: true
    dns01RecursiveNameservers: 1.1.1.1:53,9.9.9.9:53
    dns01RecursiveNameserversOnly: true
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
      - "1.1.1.1"
      - "9.9.9.9"
    prometheus:
      enabled: true
      servicemonitor:
        enabled: true
