apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victorialogs
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana-v5
  datasource:
    name: VictoriaLogs
    type: victoriametrics-logs-datasource
    uid: victorialogs
    access: proxy
    url: http://victoria-logs.observability.svc.cluster.local:9428
    isDefault: false
  plugins:
  - name: victoriametrics-logs-datasource
    version: 0.30.1
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: prometheus
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana-v5
  datasource:
    name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus-operated.observability.svc.cluster.local:9090
    isDefault: true
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: home-assistant-metrics
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana-v5
  datasource:
    name: Home Assistant Metrics
    type: prometheus
    uid: victoriametrics-ha
    access: proxy
    url: http://victoria-metrics-ha.observability.svc.cluster.local:8428
    isDefault: false
    jsonData:
      prometheusType: VictoriaMetrics
      prometheusVersion: 1.149.0
---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana-v5
  datasource:
    name: Alertmanager
    type: alertmanager
    uid: alertmanager
    access: proxy
    url: http://alertmanager-operated.observability.svc.cluster.local:9093
    jsonData:
      implementation: prometheus
