# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./configmap.yaml
- ./rbac.yaml
- ./grafana.yaml
- ./pdb.yaml
- ./servicemonitor.yaml
- ./canary-resources.yaml
- ./datasources.yaml
- ./hermes-telemetry-dashboard.yaml
