apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: home-assistant
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/controller: home-assistant
      app.kubernetes.io/name: home-assistant