# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openviking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: openviking-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OPENVIKING_CONF_CONTENT: |
          {
            "server": {
              "host": "0.0.0.0",
              "port": 1933,
              "auth_mode": "api_key",
              "root_api_key": "{{ .ROOT_API_KEY }}",
              "cors_origins": ["https://openviking.${HOME_DOMAIN}"]
            },
            "storage": {
              "workspace": "/app/.openviking/data",
              "agfs": {"backend": "local"},
              "vectordb": {"name": "context", "backend": "local"}
            },
            "embedding": {
              "dense": {
                "api_base": "https://api.openai.com/v1",
                "api_key": "{{ .OPENAI_API_KEY }}",
                "provider": "openai",
                "dimension": 1536,
                "model": "text-embedding-3-small"
              }
            },
            "vlm": {
              "api_base": "https://api.openai.com/v1",
              "api_key": "{{ .OPENAI_API_KEY }}",
              "provider": "openai",
              "model": "gpt-5.4"
            }
          }
  dataFrom:
  - extract:
      key: openviking
