#!/usr/bin/env python3
"""Generate only K8S-92 infrastructure app-local recovery assets. --check is read-only."""
import argparse
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
IMAGE = 'docker.io/library/python:3.13-alpine@sha256:399babc8b49529dabfd9c922f2b5eea81d611e4512e3ed250d75bd2e7683f4b0'
APPS = {'atproto-pds': {'namespace': 'services',
    'workloads': ['deployments/atproto-pds'], 'pvcs': ['atproto-pds']}}


def resource(api, kind, name, **fields):
    return {'apiVersion': api, 'kind': kind, 'metadata': {'name': name}, **fields}


def documents(app, config):
    name = app + '-capture'
    # Jobs have only this app's scale rights. No secrets/read or pods/exec rights.
    rules = [{'apiGroups': [''], 'resources': ['configmaps'], 'verbs': ['get', 'create', 'update']},
             {'apiGroups': [''], 'resources': ['pods', 'persistentvolumeclaims'], 'verbs': ['get', 'list']},
             {'apiGroups': [''], 'resources': ['persistentvolumeclaims'], 'verbs': ['create']},
             {'apiGroups': ['batch'], 'resources': ['jobs'], 'verbs': ['create', 'get', 'update']},
             {'apiGroups': ['snapshot.storage.k8s.io'], 'resources': ['volumesnapshots'], 'verbs': ['get', 'create']},
             {'apiGroups': ['kopiur.home-operations.com'], 'resources': ['snapshotpolicies', 'snapshots'], 'verbs': ['get', 'create']},
             {'apiGroups': ['helm.toolkit.fluxcd.io'], 'resources': ['helmreleases'], 'resourceNames': [app], 'verbs': ['get']}]
    for workload in config['workloads']:
        kind, target = workload.split('/')
        rules.append({'apiGroups': ['apps'], 'resources': [kind],
                      'resourceNames': [target], 'verbs': ['get']})
        rules.append({'apiGroups': ['apps'], 'resources': [kind + '/scale'],
                      'resourceNames': [target], 'verbs': ['get', 'update']})
    yield resource('v1', 'ServiceAccount', name)
    yield resource('rbac.authorization.k8s.io/v1', 'Role', name, rules=rules)
    yield resource('rbac.authorization.k8s.io/v1', 'RoleBinding', name,
        roleRef={'apiGroup': 'rbac.authorization.k8s.io', 'kind': 'Role', 'name': name},
        subjects=[{'kind': 'ServiceAccount', 'name': name}])
    yield resource('v1', 'ConfigMap', name, data={
        'capture.py': (ROOT / 'scripts/k8s92_infrastructure_capture.py').read_text(),
        'config.json': json.dumps(config | {'app': app, 'image': IMAGE, 'quiesceSeconds': 180,
            'expectedReplicas': {ref: 3 if ref == 'statefulsets/adguard-home' else 1 for ref in config['workloads']}})})
    yield resource('batch/v1', 'CronJob', name, spec={
        'suspend': True, 'schedule': '0 0 * * *', 'concurrencyPolicy': 'Forbid',
        'successfulJobsHistoryLimit': 1, 'failedJobsHistoryLimit': 3,
        'jobTemplate': {'spec': {'activeDeadlineSeconds': 7200, 'backoffLimit': 0,
            'ttlSecondsAfterFinished': 86400, 'template': {'spec': {
                'serviceAccountName': name, 'restartPolicy': 'Never',
                'securityContext': {'runAsNonRoot': True, 'runAsUser': 65534, 'runAsGroup': 65534,
                                    'seccompProfile': {'type': 'RuntimeDefault'}},
                'containers': [{'name': 'capture', 'image': IMAGE,
                    'command': ['python3', '/capture/capture.py', 'capture'],
                    'env': [{'name': 'CAPTURE_JOB_NAME', 'valueFrom': {'fieldRef':
                        {'fieldPath': "metadata.labels['batch.kubernetes.io/job-name']"}}}],
                    'securityContext': {'allowPrivilegeEscalation': False, 'readOnlyRootFilesystem': True,
                                        'capabilities': {'drop': ['ALL']}},
                    'resources': {'requests': {'cpu': '25m', 'memory': '64Mi'}, 'limits': {'memory': '128Mi'}},
                    'volumeMounts': [{'name': 'code', 'mountPath': '/capture', 'readOnly': True}]}],
                'volumes': [{'name': 'code', 'configMap': {'name': name}}]}}}}})


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    failed = []
    for app, config in APPS.items():
        path = ROOT / 'kubernetes/apps' / config['namespace'] / app / 'app/kopiur-capture.yaml'
        text = '# Generated by scripts/k8s92_generate_infrastructure.py; do not edit.\n' + '\n---\n'.join(
            json.dumps(doc, indent=2) for doc in documents(app, config)) + '\n'
        if args.check:
            if not path.exists() or path.read_text() != text:
                failed.append(str(path))
        else:
            path.write_text(text)
    if failed:
        sys.exit('stale app-local assets: ' + ', '.join(failed))
    print('infrastructure assets match' if args.check else 'generated infrastructure assets')


if __name__ == '__main__':
    main()
