# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  postRenderers:
  - kustomize:
      images:
      - name: ghcr.io/cloudnative-pg/cloudnative-pg
        newName: ghcr.io/cloudnative-pg/cloudnative-pg
        # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/cloudnative-pg
        newTag: 1.29.1@sha256:0dfff19ba7b52ca25851a1010028b6940fff2e233290465af1cfb08a5f3f4661
  dependsOn:
  - name: openebs
    namespace: openebs-system
  values:
    crds:
      create: true
    monitoring:
      podMonitorEnabled: false
      grafanaDashboard:
        create: true
