# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mosquitto
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: mosquitto-secret
  data:
  - secretKey: admin-username
    remoteRef:
      key: mosquitto
      property: ADMIN_USERNAME
  - secretKey: admin-password
    remoteRef:
      key: mosquitto
      property: ADMIN_PASSWORD
