# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
# renovate: datasource=github-releases depName=rabbitmq/cluster-operator
- https://github.com/rabbitmq/cluster-operator/releases/download/v2.22.0/cluster-operator-ghcr-io.yml
