apiVersion: v1
kind: Secret
metadata:
  name: {{ include "firecrawl.fullname" . }}-secret
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.secret.OPENAI_API_KEY | b64enc | quote }}
  SLACK_WEBHOOK_URL: {{ .Values.secret.SLACK_WEBHOOK_URL | b64enc | quote }}
  LLAMAPARSE_API_KEY: {{ .Values.secret.LLAMAPARSE_API_KEY | b64enc | quote }}
  BULL_AUTH_KEY: {{ .Values.secret.BULL_AUTH_KEY | b64enc | quote }}
  TEST_API_KEY: {{ .Values.secret.TEST_API_KEY | b64enc | quote }}
  FIRE_ENGINE_BETA_URL: {{ .Values.secret.FIRE_ENGINE_BETA_URL | b64enc | quote }}
  SUPABASE_ANON_TOKEN: {{ .Values.secret.SUPABASE_ANON_TOKEN | b64enc | quote }}
  SUPABASE_URL: {{ .Values.secret.SUPABASE_URL | b64enc | quote }}
  SUPABASE_SERVICE_TOKEN: {{ .Values.secret.SUPABASE_SERVICE_TOKEN | b64enc | quote }}
  PROXY_PASSWORD: {{ .Values.secret.PROXY_PASSWORD | b64enc | quote }}
  SELF_HOSTED_WEBHOOK_HMAC_SECRET: {{ .Values.secret.SELF_HOSTED_WEBHOOK_HMAC_SECRET | b64enc | quote }}
  REDIS_PASSWORD: {{ .Values.secret.REDIS_PASSWORD | b64enc | quote }}
  {{- range $k, $v := .Values.secret.extra }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
