# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
spec:
  interval: 10m
  releaseName: flux-operator
  chartRef:
    kind: OCIRepository
    name: flux-operator
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: ghcr.io/controlplaneio-fluxcd/flux-operator
      # renovate: datasource=docker depName=ghcr.io/controlplaneio-fluxcd/flux-operator
      tag: v0.57.0@sha256:7baa2697d3c4d81007c02302c55a8601f02ad2052df5952b95f8a6708c7be131
    priorityClassName: system-cluster-critical
    web:
      enabled: false
      networkPolicy:
        create: false
      rbac:
        createRoles: false
    serviceMonitor:
      create: true
      interval: 60s
      scrapeTimeout: 30s
