# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: tailscale-operator
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    oauthSecretVolume:
      secret:
        secretName: operator-oauth
    operatorConfig:
      image:
        repository: ghcr.io/tailscale/k8s-operator
        tag: v1.102.2@sha256:eaef921470ada74a84ca8bbbf4a6a89452ed2581d51a0551758507aca8dc2a01
        digest: sha256:eaef921470ada74a84ca8bbbf4a6a89452ed2581d51a0551758507aca8dc2a01
      hostname: titans-tailscale-operator
      defaultTags:
      - tag:k8s-operator
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 256Mi
    proxyConfig:
      image:
        repository: ghcr.io/tailscale/tailscale
        tag: v1.102.2@sha256:321ce041508c19079b57a28b6666c8d81ab0b08accc0a2585b3ab663d557ac24
        digest: sha256:321ce041508c19079b57a28b6666c8d81ab0b08accc0a2585b3ab663d557ac24
      defaultTags: tag:k8s
