# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: tailscale-operator
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    oauthSecretVolume:
      secret:
        secretName: operator-oauth
    operatorConfig:
      image:
        repository: ghcr.io/tailscale/k8s-operator
        tag: v1.98.9
        digest: sha256:8b2f914d0cc947c38853c16c212c8a10e0294292b23950a65dfca4d319eb12ce
      hostname: titans-tailscale-operator
      defaultTags:
      - tag:k8s-operator
      resources:
        requests:
          cpu: 10m
          memory: 64Mi
        limits:
          memory: 256Mi
    proxyConfig:
      image:
        repository: ghcr.io/tailscale/tailscale
        tag: v1.98.9
        digest: sha256:f15d5d3f4a68773a853180b72496f70ba614b64de0878c43fe3da39fe0afba47
      defaultTags: tag:k8s
