# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
configMapGenerator:
- name: ${APP}-kopiur-postgres
  files:
  - capture.sh
generatorOptions:
  disableNameSuffixHash: true
