# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  annotations:
    oci.home.arpa/allow-rollout: "true"
  name: plane
spec:
  interval: 30m
  url: oci://ghcr.io/shamubernetes/charts-mirror/plane-enterprise
  ref:
    tag: 2.6.1
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  verify:
    provider: cosign
    matchOIDCIdentity:
    - issuer: ^https://token.actions.githubusercontent.com$
      subject: ^https://github.com/shamubernetes/charts-mirror.*$
