# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pelican
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: pelican-secret
    template:
      engineVersion: v2
      data:
        APP_KEY: "{{ .APP_KEY }}"
        DB_CONNECTION: pgsql
        DB_DATABASE: pelican
        DB_HOST: postgres17-pooler-session.database.svc.cluster.local
        DB_PASSWORD: "{{ .PELICAN_POSTGRES_PASS }}"
        DB_PORT: "5432"
        DB_USERNAME: "{{ .PELICAN_POSTGRES_USER }}"
        INIT_POSTGRES_DBNAME: pelican
        INIT_POSTGRES_HOST: postgres17-pooler-session.database.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .PELICAN_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: "{{ .PELICAN_POSTGRES_USER }}"
  dataFrom:
  - extract:
      key: pelican
  - extract:
      key: cloudnative-pg
