# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  annotations:
    oci.home.arpa/allow-rollout: "true"
  name: rook-ceph-operator
spec:
  interval: 30m
  url: oci://ghcr.io/rook/rook-ceph
  ref:
    tag: v1.20.4
    digest: sha256:afa59f5afcfffe21f8bfddb6606d9e2bfbf051d546f479b7b690bff444e2da68
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
