# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: elasticsearch
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: elasticsearch-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ELASTIC_PASSWORD: "{{ .ELASTIC_PASSWORD }}"
  dataFrom:
  - extract:
      key: elasticsearch
