apiVersion: v1
kind: Secret
metadata:
    name: elasticsearch-secret
type: Opaque
stringData:
    ELASTIC_PASSWORD: ENC[AES256_GCM,data:+dydgYvNBgUOB1R2zsl5NMjsaQVuPkCNntr4MmVl4tJ6CTA9JcyucvKodyM4eBFO,iv:0sgUT8td8FUKSkpeWFBsBCPvkryCAiNKXDHKExntDB0=,tag:p569xNhsF7kWwxYRPHlu7w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCbUpqcHA1NTRrQ2NIL3RG
            NEpuWDNLMnZzdVZrcEM5L3VkZjk2V25FaHhJCk5xYURBRjByVVZySWlpRU41S0Jl
            eUxqRjlDSFdiNDI5MU9wVVJIYzlNZk0KLS0tIFZsUG5yQkpqMU4zWElXZEU1SlAx
            bW55UHJIR2pmNUZKMU9NakVkVnJna2cKppaX9CRA+aw1z6WpnLzyVkk7IVVpnqq7
            3TayISTe9i4mapWKZRlLIAsYSL5wskiOAmeRZH581MOzBCtmGtdOjw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-04T04:23:30Z"
    mac: ENC[AES256_GCM,data:Wu4okTSLKLQFszgHQv91h7rXqMfqvF5UsOMyoRx4SalJPcpzf8PGctyQK3if1+A11fEfgFoXCjOjoBW2v8yA/fUROM6Oz95AZUB0mVmor1s8LUVAHqtPD8sO4i2jk8V2wjigj2F5brgYJbrVH0Jclcy8B8UGWWk0FKAZ6/8dYXs=,iv:cqFEu6UFDbWspcUextpkyFWyIFFFDDZxy9fgIIACiLI=,tag:Gv4MgCns5RkxQ/csupdOsQ==,type:str]
    version: 3.13.1
