# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: reflector
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: docker.io/emberstack/kubernetes-reflector
      tag: 10.0.62@sha256:03447c52087c10bbff4385a6b5686d81aabec8cdb3bfcf81f5996428b30d6478
