# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: reflector
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: docker.io/emberstack/kubernetes-reflector
      tag: 10.0.61@sha256:c73a88f96b24b958ecd138f3e77caae3350c969fbb3aec302f72de2013db180b
