# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: reflector
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: docker.io/emberstack/kubernetes-reflector
      tag: 10.0.64@sha256:35d98aa901165ea3817e41626c31a60d0cb9c9c4137d1b742d4cb4d590e8c52e
