# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: external-secrets
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  postRenderers:
  - kustomize:
      images:
      - name: ghcr.io/external-secrets/external-secrets
        newName: ghcr.io/external-secrets/external-secrets
        # renovate: datasource=docker depName=ghcr.io/external-secrets/external-secrets
        newTag: v2.8.0@sha256:24c0dd3699e0988520afd2218612758cd97d1f702757b5b4fcf89adaa33ef679
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    serviceMonitor:
      enabled: true
      interval: 1m
