# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: external-secrets
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  postRenderers:
  - kustomize:
      images:
      - name: ghcr.io/external-secrets/external-secrets
        newName: ghcr.io/external-secrets/external-secrets
        # renovate: datasource=docker depName=ghcr.io/external-secrets/external-secrets
        newTag: v2.10.0@sha256:814117b0fd6d121b03e8ba3b6db1cecbe7449a354fc0fc9c4faf73a37aa221b1
  uninstall:
    keepHistory: false
  values:
    installCRDs: true
    serviceMonitor:
      enabled: true
      interval: 1m
