# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: openebs
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    alloy:
      configReloader:
        image:
          digest: sha256:959d47672fbff2776a04ec62b8afcec89e8c036af84dc5fade50019dab212746
      image:
        digest: sha256:7790f6f7fbd8e4486b4b6c6fc6a7293a73605bb79aaa7f49003cb366943724f6
    loki:
      enabled: false
    minio:
      enabled: false
    localpv-provisioner:
      helperPod:
        image:
          tag: 4.6.0@sha256:a3043d266b1c06fb42377ced0c3fc190c66e1e83ae1efda7670ed73feb4ede14
      localpv:
        image:
          registry: quay.io/
          tag: 4.6.0@sha256:99f5116f5cb83fb9d046ef5ff5b8ea98da90e7da5250d7b101bd650662238a0a
        basePath: &hostPath /var/openebs/local
      hostpathClass:
        enabled: true
        name: openebs-hostpath
        isDefaultClass: false
        basePath: *hostPath
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
          keep: false
    zfs-localpv:
      enabled: false
    lvm-localpv:
      enabled: false
    mayastor:
      enabled: false
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
