# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: git-mirror-operator
  namespace: "${KS_NAMESPACE}"
spec:
  interval: "${KS_INTERVAL}"
  url: https://github.com/shamubernetes/git-mirror-operator.git
  ref:
    tag: v0.2.0

# yamllint disable-line rule:document-start
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app git-mirror-operator
  namespace: "${KS_NAMESPACE}"
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./config/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: git-mirror-operator
  wait: true
  interval: "${KS_INTERVAL}"
  retryInterval: "${KS_RETRY_INTERVAL}"
  timeout: "${KS_TIMEOUT}"
  images:
  - name: ghcr.io/shamubernetes/git-mirror-operator
    newTag: v0.2.0
    digest: sha256:744df24a053706aafb2e92bd4b1f7185342af661874a13b71bd53cc40cdf1d75
  patches:
  - target:
      kind: Deployment
      labelSelector: control-plane=controller-manager
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: ghcr.io/shamubernetes/git-mirror-sync:v0.2.0@sha256:26464501914c3534b23c6e0375ab72b4033334842763e5da8f28800a5e744c5b

# yamllint disable-line rule:document-start
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app git-mirror-operator-config
  namespace: "${KS_NAMESPACE}"
spec:
  targetNamespace: &namespace git-mirror-operator-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
  - name: external-secrets-secret-store
  - name: git-mirror-operator
  path: ./kubernetes/apps/services/git-mirror-operator/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: "${KS_GIT_REPO_NAME}"
  wait: false
  interval: "${KS_INTERVAL}"
  retryInterval: "${KS_RETRY_INTERVAL}"
  timeout: "${KS_TIMEOUT}"
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
