# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Meta - Label Sync"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
    - ".github/labels.json"
    - ".github/workflows/meta-label-sync.yaml"
  schedule:
  - cron: "0 0 * * *" # Every day at midnight

jobs:
  label-sync:
    name: Label Sync
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Sync Labels
      env:
        GH_TOKEN: ${{ github.token }}
      run: scripts/sync-github-labels .github/labels.json
