# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Schedule - Publish Schemas"

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"
  push:
    branches: ["main"]
    paths:
    - ".github/workflows/publish-schemas.yaml"
    - ".github/workflows/resources/k8s-schemas.sh"
    - ".github/workflows/resources/k8s-schema-hacks.sh"
    - ".github/workflows/resources/schema-hacks/*"
    - ".github/workflows/resources/schemas/*"
    - "kubernetes/apps/system-upgrade/tuppr/upgrades/kubernetesupgrade.yaml"
jobs:
  publish-schemas:
    name: Publish Schemas
    runs-on: ["ghar-set-zoo"]
    permissions:
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@097625b28a26ba4b7437926ab03b4d3bd2e6c3d1 # master

    - name: Setup Workflow Tools
      shell: bash
      run: brew install kubectl yq jq

    - name: Setup Python
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: "3.13"

    - name: Write kubeconfig
      id: kubeconfig
      uses: timheuer/base64-to-file@dfa5a5dd38803cb4f5c3a081eeb28e8362d43e9c # v2.0.0
      with:
        encodedString: "${{ secrets.KUBECONFIG }}"
        fileName: kubeconfig

    - name: Install Python Dependencies
      env:
        # renovate: datasource=pypi depName=openapi2jsonschema2
        SCHEMA_GENERATOR_VERSION: 1.1.37
      run: python -m pip install "openapi2jsonschema2==${SCHEMA_GENERATOR_VERSION}"

    - name: Download and run crd-extractor
      env:
        KUBECONFIG: "${{ steps.kubeconfig.outputs.filePath }}"
      shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/datreeio/CRDs-catalog/43e4407642d4c37683c88711f37caa6c9c20ca40/Utilities/crd-extractor.sh | bash

    - name: Run k8s-schemas
      shell: bash
      run: |
        mkdir -p /home/runner/schemas/kubernetes
        mkdir -p /home/runner/schemas/hacks
        ./.github/workflows/resources/k8s-schemas.sh
        ./.github/workflows/resources/k8s-schema-hacks.sh
        mv /home/runner/.datree/crdSchemas/* /home/runner/schemas
        mv ./.github/workflows/resources/schemas/* /home/runner/schemas/hacks

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
      with:
        apiToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
        accountId: "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
        workingDirectory: /home/runner/schemas
        command: pages deploy --project-name=k8s-schemas --branch main .
