# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kaneo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: kaneo-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DATABASE_URL: >-
          postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASSWORD }}@postgres17-pooler.database.svc.cluster.local:5432/kaneo?sslmode=disable
        AUTH_SECRET: "{{ .AUTH_SECRET }}"
        CUSTOM_OAUTH_CLIENT_ID: "{{ .CUSTOM_OAUTH_CLIENT_ID }}"
        CUSTOM_OAUTH_CLIENT_SECRET: "{{ .CUSTOM_OAUTH_CLIENT_SECRET }}"
        GITHUB_APP_NAME: "{{ .GITHUB_APP_NAME }}"
        GITHUB_APP_ID: "{{ .GITHUB_APP_ID }}"
        GITHUB_PRIVATE_KEY: "{{ .GITHUB_PRIVATE_KEY | b64dec }}"
        GITHUB_WEBHOOK_SECRET: "{{ .GITHUB_WEBHOOK_SECRET }}"
        SMTP_FROM: "{{ .SMTP_FROM }}"
        INIT_POSTGRES_DBNAME: kaneo
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: kaneo
  - extract:
      key: cloudnative-pg
